spring:
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: conversation-state-consumer
      auto-offset-reset: earliest

  datasource:
    url: jdbc:postgresql://localhost:5432/agent_platform
    username: agent
    password: agent

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai/v1
      chat:
        options:
          model: openai/gpt-oss-20b

order-service:
  base-url: http://localhost:5001